version: "3.5"
services:
  haproxy:
    image: "haproxy:2.2-bullseye"
    ports:
      - 5672:5672
      - 15672:15672
      - 8080:8080
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
